add support for LTE interface
nshttpd/mikrotik-exporter pull request #99
Opened 2020-11-21 23:42 UTC by mastier

Hi,
I hope you find it useful. I made a sincere rip-off from wlanif_collector.go for supporting lte interface parameters like RSSI, RSRP, RSRQ, SINR.

2021-01-15 18:51 UTC, lexfrei commented
Great work!

@nshttpd, can you merge this PR plz?

2021-02-19 19:36 UTC, paran1 commented
This patch was just what I needed. It works perfectly, thanks!

I only monitor a single device: wAP R ac with a R11e-LTE6 modem.

2021-03-23 02:56 UTC, nshttpd commented
@mastier .. I've realized that I'm not dead. Looks like there are conflicts now that I've started catching up on PRs. Can you pull master and rebase to see if that's an easy fix for the conflicts?

2021-03-23 13:20 UTC, mastier commented
@nshttpd good to hear you alive :-) I've rebased my branch with the current master. In case of issues let me know.

2021-03-25 00:42 UTC, nshttpd requested changes
Just the one thing for the config test from possibly some missed copy-pasta.

2021-03-25 00:42 UTC, nshttpd commented on config/config_test.go
> +	assertFeature("Lte", c.Features.Ipsec, t)
Shouldn't this be `c.Features.Lte`?

2021-03-25 19:14 UTC, mastier commented on config/config_test.go
> +	assertFeature("Lte", c.Features.Ipsec, t)
> Shouldn't this be `c.Features.Lte`?

Yes. My bad. Sent fix.

2021-03-26 00:04 UTC, nshttpd approved these changes

2021-03-26 00:05 UTC, merged

2021-03-26 00:05 UTC, nshttpd commented
Sweet. Thanks @mastier. Sorry this took me so long to get around to.